export const SET_TODO_INPUT = 'set_todo-input'
export const ADD_TODO = 'add_todo'
export const REMOVE_TODO = 'remove_todo'
export const SET_TODO_EDIT = 'set_todo_edit'
export const SET_CONTENT = 'set_content'
export const UPDATE_TODO = 'update_todo'
